# =========================
# SERVER
# =========================

server.port=8083

# =========================
# MYSQL
# =========================

spring.datasource.url=jdbc:mysql://localhost:3306/animebackend?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh

spring.datasource.username=root

spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# JWT
# =========================

jwt.secret=${JWT_SECRET}

jwt.expiration=604800000

jwt.refresh-expiration=2592000000

# =========================
# FILE UPLOAD
# =========================

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =========================
# MAIL
# =========================

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}

spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# GOOGLE LOGIN
# =========================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}


spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile

# =========================
# OPENAI
# =========================

openai.api.key=${OPENAI_API_KEY}

# =========================
# VNPAY
# =========================

vnpay.tmn-code=DEMO123

vnpay.hash-secret=VNPAY_SECRET_KEY_DEMO

vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

vnpay.return-url=http://localhost:8083/api/vnpay/payment-callback

# =========================
# SWAGGER
# =========================

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/v3/api-docs
spring.servlet.multipart.enabled=true
